# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/tb248952/Documents/Linux_Unreal_Engine_5.5.4

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	ros2_sandbox-Android-DebugGame  \
	ros2_sandbox-Android-Development  \
	ros2_sandbox-Android-Shipping  \
	ros2_sandbox-Linux-DebugGame  \
	ros2_sandbox-Linux-Development  \
	ros2_sandbox-Linux-Shipping  \
	ros2_sandbox-LinuxArm64-DebugGame  \
	ros2_sandbox-LinuxArm64-Development  \
	ros2_sandbox-LinuxArm64-Shipping  \
	ros2_sandbox \
	ros2_sandboxEditor-Linux-DebugGame  \
	ros2_sandboxEditor-Linux-Development  \
	ros2_sandboxEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ros2_sandboxEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ros2_sandboxEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

ros2_sandbox-Android-DebugGame:
	 $(BUILD) ros2_sandbox Android DebugGame  -Project="/home/tb248952/Documents/toto/ros2_sandbox/ros2_sandbox.uproject" $(ARGS)

ros2_sandbox-Android-Development:
	 $(BUILD) ros2_sandbox Android Development  -Project="/home/tb248952/Documents/toto/ros2_sandbox/ros2_sandbox.uproject" $(ARGS)

ros2_sandbox-Android-Shipping:
	 $(BUILD) ros2_sandbox Android Shipping  -Project="/home/tb248952/Documents/toto/ros2_sandbox/ros2_sandbox.uproject" $(ARGS)

ros2_sandbox-Linux-DebugGame:
	 $(BUILD) ros2_sandbox Linux DebugGame  -Project="/home/tb248952/Documents/toto/ros2_sandbox/ros2_sandbox.uproject" $(ARGS)

ros2_sandbox-Linux-Development:
	 $(BUILD) ros2_sandbox Linux Development  -Project="/home/tb248952/Documents/toto/ros2_sandbox/ros2_sandbox.uproject" $(ARGS)

ros2_sandbox-Linux-Shipping:
	 $(BUILD) ros2_sandbox Linux Shipping  -Project="/home/tb248952/Documents/toto/ros2_sandbox/ros2_sandbox.uproject" $(ARGS)

ros2_sandbox-LinuxArm64-DebugGame:
	 $(BUILD) ros2_sandbox LinuxArm64 DebugGame  -Project="/home/tb248952/Documents/toto/ros2_sandbox/ros2_sandbox.uproject" $(ARGS)

ros2_sandbox-LinuxArm64-Development:
	 $(BUILD) ros2_sandbox LinuxArm64 Development  -Project="/home/tb248952/Documents/toto/ros2_sandbox/ros2_sandbox.uproject" $(ARGS)

ros2_sandbox-LinuxArm64-Shipping:
	 $(BUILD) ros2_sandbox LinuxArm64 Shipping  -Project="/home/tb248952/Documents/toto/ros2_sandbox/ros2_sandbox.uproject" $(ARGS)

ros2_sandbox: ros2_sandbox-Linux-Development

ros2_sandboxEditor-Linux-DebugGame:
	 $(BUILD) ros2_sandboxEditor Linux DebugGame  -Project="/home/tb248952/Documents/toto/ros2_sandbox/ros2_sandbox.uproject" $(ARGS)

ros2_sandboxEditor-Linux-Development:
	 $(BUILD) ros2_sandboxEditor Linux Development  -Project="/home/tb248952/Documents/toto/ros2_sandbox/ros2_sandbox.uproject" $(ARGS)

ros2_sandboxEditor: ros2_sandboxEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/tb248952/Documents/toto/ros2_sandbox/ros2_sandbox.uproject" -Game 

.PHONY: $(TARGETS)
